# Generated by Django 5.2.8 on 2025-11-29 20:55

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(choices=[('CLIENTE', 'Cliente'), ('FINANCEIRO', 'Financeiro'), ('LOGISTICA', 'Logística'), ('POS_VENDA', 'Pós Venda'), ('ADMIN', 'Administrador')], default='CLIENTE', max_length=20),
        ),
    ]
